### ISSUE TITLE
FieldError: Page doesn't have level in Django 1.8.7 and Django CMS 3.4

### ISSUE THREAD

**Issue by snejy** [raphaa/cmsplugin-htmlsitemap#10]
Just after adding the plugin occured FieldError.. `Cannot resolve keyword 'level' into field. Choices are: application_namespace, application_urls..`

**Comment by dmodules** [comment]
Did you find solution for this? I think this plugin does not work with django cms 3.

**Comment by snejy** [comment]
It should be okay with django-cms==3.1 because it still works with mptt.. For fix the template and cms_plugins should be reworked but I dont think there is a tree_info templatetag equivalent in treebeard for now.

**Comment by dmodules** [comment]
Do you still have this bug?

**Comment by raphaa** [comment]
For CMS 3.2, I've planned a new plugin from scratch but unfortunately had no time to do this.

**Comment by snejy** [comment]
I've found djangocms-htmlsitemap which works with CMS above 3.2 but lacks some of the filters like created_by etc. https://pypi.python.org/pypi/djangocms-htmlsitemap/

**Comment by dmodules** [comment]
Thank you! :)

Martin

**Comment by jedie** [comment]
Get the same error "Cannot resolve keyword 'level' into field." with 'master' and CMS 3.3  :(

Is this project alive?!?

**Comment by jasjukaitis** [comment]
I've abandoned this project. As @jedie linked, please use djangocms-htmlsitemap now.
