### ISSUE TITLE
Change table name to support CMS 3.1

### ISSUE THREAD

**Issue by kayluhb** [raphaa/cmsplugin-htmlsitemap#9]
DeprecationWarning: please rename the table "cmsplugin_htmlsitemap" to "cmsplugin_htmlsitemap_htmlsitemap" in cmsplugin_htmlsitemap

The compatibility code will be removed in 3.1
bad_table_name, proper_table_name, model._meta.app_label), DeprecationWarning)

**Comment by jasjukaitis** [comment]
I've abandoned this project. Please use https://github.com/kapt-labs/djangocms-htmlsitemap
